version: '3.7'
services:
  postgres:
    container_name: postgres_turnout
    image: postgres:11.5
    environment:
      - POSTGRES_DB=turnout
      - POSTGRES_PASSWORD=turnout
    ports:
      - "5432:5432"
    volumes:
      - pgdata_turnout:/var/lib/postgresql/data

  redis:
    container_name: redis_turnout
    image: 'redis:5.0.5'
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata_turnout:/data

  server:
    build: .
    entrypoint: wait-for-it postgres:5432 redis:6379 --
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "9001:8000"
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=turnout.settings
      - DATABASE_URL=pgsql://postgres:turnout@postgres:5432/turnout
      - ALLOWED_HOSTS=*
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: .
      dockerfile: Dockerfile-client-dev
    command: npm run develop
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "35729:35729"

volumes:
  pgdata_turnout:
  redisdata_turnout:
